apiVersion: v1
kind: List
metadata:
  name: featureflagsetld-controller-list
  annotations:
    razee.io/git-repo: "{{{GIT_REMOTE}}}"
    razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
    version: "{{TRAVIS_COMMIT}}"
type: array
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: featureflagsetld-controller
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: featureflagsetld-controller
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: featureflagsetld-controller
          name: featureflagsetld-controller
        spec:
          serviceAccountName: razeedeploy-sa
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          containers:
          - image: "quay.io/razee/featureflagsetld:{{TRAVIS_TAG}}"
            resources:
              limits:
                memory: 200Mi
                cpu: 100m
              requests:
                memory: 75Mi
                cpu: 40m
            imagePullPolicy: Always
            name: featureflagsetld-controller
            livenessProbe:
              exec:
                command:
                - sh/liveness.sh
              initialDelaySeconds: 30
              periodSeconds: 150
              timeoutSeconds: 30
              failureThreshold: 1

  - apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      # name must match the spec fields below, and be in the form: <plural>.<group>
      name: featureflagsetsld.deploy.razee.io
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
    spec:
      # group name to use for REST API: /apis/<group>/<version>
      group: deploy.razee.io
      # list of versions supported by this CustomResourceDefinition
      versions:
        - name: v1alpha1
          # Each version can be enabled/disabled by Served flag.
          served: true
          # One and only one version must be marked as the storage version.
          storage: true
      # either Namespaced or Cluster
      scope: Namespaced
      names:
        # plural name to be used in the URL: /apis/<group>/<version>/<plural>
        plural: featureflagsetsld
        # singular name to be used as an alias on the CLI and for display
        singular: featureflagsetld
        # kind is normally the CamelCased singular type. Your resource manifests use this.
        kind: FeatureFlagSetLD
        # shortNames allow shorter string to match your resource on the CLI
        shortNames:
        - ffsld
      subresources:
        # status enables the status subresource.
        status: {}
      validation:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          properties:
            spec:
              type: object
              required: [sdk-key]
              properties:
                sdk-key:
                  type: string
                identity:
                  oneOf:
                  - type: string
                  - type: array
                    items:
                      oneOf:
                      - type: string
                      - type: object
                        required: [valueFrom]
                        properties:
                          valueFrom:
                            type: object
                            required: [configMapKeyRef]
                            properties:
                              configMapKeyRef:
                                type: object
                                required: [name, key]
                                properties:
                                  name:
                                    type: string
                                  key:
                                    type: string
                                  type:
                                    type: string
