language: node_js
dist: focal
node_js:
  - 18

services:
  - docker

env:
  global:
    - GITHUB_TOKEN="${PUBLIC_GITHUB_TOKEN_2024_08_20}"

before_install:
  - echo "$DOCKERHUB_TOKEN" | docker login -u "icdevops" --password-stdin
  - export WS_APIKEY=${WS_APIKEY}
  - export WS_USERKEY=${WS_USERKEY}
  - export WS_PRODUCTNAME=${WS_PRODUCTNAME}
  - export WS_PROJECTNAME=FeatureFlagSetLD
  - export WS_WSS_URL=https://ibmets.whitesourcesoftware.com/agent
  - ./build/download-kubelint.sh

script:
  # Audit npm packages. Fail build whan a PR audit fails, otherwise report the vulnerability and proceed.
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --config audit-ci.json; else npx audit-ci --config audit-ci.json || true; fi
  - npm run lint
  - npm test
  - docker build --rm -t "quay.io/razee/featureflagsetld:${TRAVIS_COMMIT}" .
  - if [ -n "${TRAVIS_TAG}" ]; then docker tag quay.io/razee/featureflagsetld:${TRAVIS_COMMIT} quay.io/razee/featureflagsetld:${TRAVIS_TAG}; fi
  - docker images
  - ./build/process-template.sh kubernetes/FeatureFlagSetLD/resource.yaml >/tmp/resource.yaml
  - kubelint /tmp/resource.yaml
  - if [[ "${TRAVIS_TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then npm version --no-git-tag-version "${TRAVIS_TAG}"; fi
  # Perform UA scan on non-PR builds
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar; java -jar wss-unified-agent.jar -d . || echo "UA Scan Error occurred"; fi

before_deploy:
  - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io
  # Use npm v9 for deployments (v10 has problems with authentication with api_key)
  - npm install -g npm@9
  # Workaround ruby gem problem https://travis-ci.community/t/deployments-are-failing-due-to-uri-dependency/14375/4
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install logger

deploy:
  # Deploy alpha builds
  - provider: script
    script: docker push "quay.io/razee/featureflagsetld:${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$

  # Deploy released builds
  - provider: script
    script: docker push "quay.io/razee/featureflagsetld:${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: releases
    file: /tmp/resource.yaml
    skip_cleanup: true
    api_key: "${GITHUB_TOKEN}"
    name: "${TRAVIS_TAG}"
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: npm
    email: "${NPMJS_EMAIL}"
    api_key: "${NPMJS_API_KEY}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
